### ISSUE TITLE
Docs Correction

### ISSUE THREAD

**Issue by lingeringwillx** [actioninja/refpack-rs#4]
https://github.com/actioninja/refpack-rs/blob/624e7bf975ad66a35753decfffac317d57162860/src/format.rs#L81

I think this is meant to be The Sims 3?

**Comment by lingeringwillx** [comment]
Also btw The Sims 4 doesn't use the RefPack/QFS algorithm. It uses the standard deflate algorithm.

**Comment by lingeringwillx** [comment]
One last thing is I don't think that The Sims 1 used Refpack. The Sims Online did.

**Comment by actioninja** [comment]
Typed something longer up and then accidentally refreshed the page and ate it.

It looks like you're correct actually, I made this for the sims purposes so never actually properly tested simcity 4 or verified against other implementations for simcity 4, bitmasking code is such a pain to read.

I really need to make a properly up to date reference for this stuff that isn't inaccurate, most wikis like simswiki and niotso are "locked" wikis and I can't fix myself easily.

**Comment by actioninja** [comment]
> Also btw The Sims 4 doesn't use the RefPack/QFS algorithm. It uses the standard deflate algorithm.

Good to know, unfortunately probably going to need to push a breaking change to rename the formats.

> One last thing is I don't think that The Sims 1 used Refpack. The Sims Online did.

If I'm going to do a breaking change, I'd prefer to do it in one batch. Got some source reference for this?

**Comment by lingeringwillx** [comment]
> If I'm going to do a breaking change, I'd prefer to do it in one batch. Got some source reference for this?

I don't have a good source for this. It's just that The Sims Online port [FreeSO](https://github.com/riperiperi/FreeSO) has compression code, while The Sims 1's port [Simitone](https://github.com/riperiperi/Simitone) doesn't.

**Comment by chieltbest** [comment]
The sims 4 does use DEFLATE for most of it's packages, but I believe that it does support refpack compression, and that some of it's internal files do (or used to, I'm not sure) use refpack compression.

I'm making an install of the sims 4 right now to verify it, I'll post results later today or tomorrow.
Sadly I can't check if the sims 4 actually supports refpack by making a custom package, because my library doesn't support writing files (yet). :)

**Comment by chieltbest** [comment]
Alright here is my source for why I included the sims 4 in my pull request that added sims 3/4 support: https://modthesims.info/showthread.php?t=533094

This is an official EA sims 4 modding example and the zip (TS4_Custom_Content_Guide.zip, for future reference) includes an example "simsmodsquad-novelist.package" that is encoded 100% in refpack. I would assume that the game can read this package though I haven't verified that.
I also just checked that the index entries in this file all do use the sims 3/4 encoding format.

**Comment by lingeringwillx** [comment]
Ok, it does seem to support both deflate and qfs. Looking at some old code:

https://github.com/s4ptacle/Sims4Tools/blob/fff19365a12711879bad26481a393a6fbc62c465/s4pi/Package/Compression.cs#L49-L56

So this was misinformation on my part :p

**Comment by chieltbest** [comment]
Alright just for future reference in case anyone tries to google this in the future, here is a list of all the .package files in the default steam installation of the game that use refpack encoding (each of these package files include only a single refpack encoded entry):

- Data/Client/Strings_ENG_US.package
- Data/Client/thumbnails.package
- Data/Simulation/SimulationFullBuild0.package
- Delta/EP01/Strings_ENG_US.package
- Delta/EP02/Strings_ENG_US.package
- Delta/EP03/Strings_ENG_US.package
- Delta/EP04/Strings_ENG_US.package
- Delta/EP05/Strings_ENG_US.package
- Delta/EP06/Strings_ENG_US.package
- Delta/EP07/Strings_ENG_US.package
- Delta/EP08/Strings_ENG_US.package
- Delta/EP09/Strings_ENG_US.package
- Delta/EP10/Strings_ENG_US.package
- Delta/EP11/Strings_ENG_US.package
- Delta/EP12/Strings_ENG_US.package
- Delta/EP13/Strings_ENG_US.package
- Delta/EP14/Strings_ENG_US.package
- Delta/GP01/Strings_ENG_US.package
- Delta/GP02/Strings_ENG_US.package
- Delta/GP03/Strings_ENG_US.package
- Delta/GP04/Strings_ENG_US.package
- Delta/GP05/Strings_ENG_US.package
- Delta/GP06/Strings_ENG_US.package
- Delta/GP07/Strings_ENG_US.package
- Delta/GP08/Strings_ENG_US.package
- Delta/GP09/Strings_ENG_US.package
- Delta/GP10/Strings_ENG_US.package
- Delta/GP11/Strings_ENG_US.package
- Delta/GP12/Strings_ENG_US.package
- Delta/SP01/Strings_ENG_US.package
- Delta/SP02/Strings_ENG_US.package
- Delta/SP03/Strings_ENG_US.package
- Delta/SP04/Strings_ENG_US.package
- Delta/SP05/Strings_ENG_US.package
- Delta/SP06/Strings_ENG_US.package
- Delta/SP07/Strings_ENG_US.package
- Delta/SP08/Strings_ENG_US.package
- Delta/SP09/Strings_ENG_US.package
- Delta/SP10/Strings_ENG_US.package
- Delta/SP11/Strings_ENG_US.package
- Delta/SP12/Strings_ENG_US.package
- Delta/SP13/Strings_ENG_US.package
- Delta/SP14/Strings_ENG_US.package
- Delta/SP15/Strings_ENG_US.package
- Delta/SP16/Strings_ENG_US.package
- Delta/SP17/Strings_ENG_US.package
- Delta/SP18/Strings_ENG_US.package
- Delta/SP21/Strings_ENG_US.package
- Delta/SP22/Strings_ENG_US.package
- Delta/SP23/Strings_ENG_US.package
- Delta/SP25/Strings_ENG_US.package
- Delta/SP29/Strings_ENG_US.package
- Delta/SP31/Strings_ENG_US.package
- Delta/SP33/Strings_ENG_US.package
- Delta/SP34/Strings_ENG_US.package
- Delta/SP35/Strings_ENG_US.package
- Delta/SP36/Strings_ENG_US.package
- Delta/SP37/Strings_ENG_US.package
- Delta/SP38/Strings_ENG_US.package
- Delta/SP39/Strings_ENG_US.package
- Delta/SP40/Strings_ENG_US.package
- Delta/SP41/Strings_ENG_US.package
- Delta/SP43/Strings_ENG_US.package
- Delta/SP45/Strings_ENG_US.package

**Comment by actioninja** [comment]
> > If I'm going to do a breaking change, I'd prefer to do it in one batch. Got some source reference for this?
> 
> I don't have a good source for this. It's just that The Sims Online port [FreeSO](https://github.com/riperiperi/FreeSO) has compression code, while The Sims 1's port [Simitone](https://github.com/riperiperi/Simitone) doesn't.

Simitone is a pretty lightweight frontend around FreeSO, all of the content loading is inside FreeSO. Examining the `far` files from a Sims 1 install is yielding lots of 10 FB` byte sequences followed by blocks that look a lot like refpack, I'm not sure about this one.

**Comment by lingeringwillx** [comment]
> > > If I'm going to do a breaking change, I'd prefer to do it in one batch. Got some source reference for this?
> > 
> > 
> > I don't have a good source for this. It's just that The Sims Online port [FreeSO](https://github.com/riperiperi/FreeSO) has compression code, while The Sims 1's port [Simitone](https://github.com/riperiperi/Simitone) doesn't.
> 
> Simitone is a pretty lightweight frontend around FreeSO, all of the content loading is inside FreeSO. Examining the `far` files from a Sims 1 install is yielding lots of `10 FB` byte sequences followed by blocks that look a lot like refpack, I'm not sure about this one.

I see, so I guess this is another wrong assumption.
